### ISSUE TITLE
Native TF2IDB_CustomQuery was not found.

### ISSUE THREAD

**Issue by Temmiekat** [punteroo/TF2-Item-Plugins#1]
**Describe the bug**
when loading the tf2 server the plugin vip-unusuals.smx will fail to load giving the error 
"[SM] Unable to load plugin "vip-unusuals.smx": Native "TF2IDB_CustomQuery" was not found

**To Reproduce**
1. Go to 'server manager'
2. Click on 'start server'
3. Scroll down to 'Initializing Steam Libraries
'

**Screenshots**
![Screenshot (3)](https://user-images.githubusercontent.com/58391871/107737768-39e2db80-6cd3-11eb-9633-d47816713074.png)

**Comment by punteroo** [comment]
Hello thanks for writing this issue and getting in contact.

That error means you do not have FlaminSarge's TF2IDB which has ``TF2IDB_CustomQuery`` function compiled with it. This has already happened to another user so for the sake of it being easier, I'll provide a compiled version of FlaminSarge's TF2IDB on future releases.

For now, replace your TF2IDB version with the one in this repo which will work without issues: https://github.com/punteroo/TF2-Item-Plugins/blob/production/plugins/tf2idb.smx

I'll pack everything once I come home since I am currently on vacation. This issue will remain open until then.

**Comment by punteroo** [comment]
This has been fixed in the latest [v2.3.2 release](https://github.com/punteroo/TF2-Item-Plugins/releases/tag/v2.3.2).

Please, do read the new [installation instructions](https://github.com/punteroo/TF2-Item-Plugins#installation) to prevent any future issues with this.

I'll close this now, thanks for reporting!
