### ISSUE TITLE
Error with tf2item_weapons when connecting a player

### ISSUE THREAD

**Issue by DARKSIDE99199** [punteroo/TF2-Item-Plugins#26]
Every time a player connects to the server, an error appears with the tf2item_weapons.smx plugin
![image](https://github.com/punteroo/TF2-Item-Plugins/assets/151347032/120141fc-5531-47cf-a0f9-34c31cdbe213)
![image](https://github.com/punteroo/TF2-Item-Plugins/assets/151347032/604168ee-51ca-435a-9de5-d134276970bf)

**Comment by punteroo** [comment]
Hello,

The plugin pack is very old, and I hadn't planned on rewriting it all these years. However, I started last week on a complete rewrite of the plugin pack, including both weapons and cosmetics, in the [`feat/rewrite`](https://github.com/punteroo/TF2-Item-Plugins/tree/feat/rewrite) branch.

Once this is completed, there will be an updated version for 2024. Many dependencies have changed over time, such as TF2Attributes and TFEconData, and there are also improvements to be made within the plugins themselves.

Please understand most things do not work as expected due to this very reason. Thanks!

**Comment by punteroo** [comment]
Hello.

Please confirm the issues reported here are gone to properly close the Issue or handle it accordingly.

**Comment by DARKSIDE99199** [comment]
Yes, the issues are solved. Thanks!
