### ISSUE TITLE
Without permission

### ISSUE THREAD

**Issue by Falow1** [punteroo/TF2-Item-Plugins#9]
I haven't activated the vip but nobody can use the plugin, when someone tries to use !weapons it says that the person doesn't have permission to use it

**Comment by punteroo** [comment]
Commands are restricted to players (by default) with the admin flag ``ADMFLAG_RESERVATION``. For a player to utilize any of the commands they must have this flag on them. More on assigning Admin Flags on players in AlliedModders' Wiki:
https://wiki.alliedmods.net/Adding_Admins_(SourceMod)

You can also use **SourceMod**'s Overrides System to bypass this command and enable it for all players, more information on AlliedModders' Wiki:
https://wiki.alliedmods.net/Overriding_Command_Access_(Sourcemod)

...or modify these 3 lines on both plugins and use [RegConsoleCmd](https://sourcemod.dev/#/console/function.RegConsoleCmd) instead of [RegAdminCmd](https://sourcemod.dev/#/console/function.RegAdminCmd) to allow anyone to use them freely, and then re-compile (Refer to [the requirements section](https://github.com/punteroo/TF2-Item-Plugins#requirements) for Compiling info)
https://github.com/punteroo/TF2-Item-Plugins/blob/production/scripting/tf2item_weapons.sp#L53-L55
https://github.com/punteroo/TF2-Item-Plugins/blob/production/scripting/tf2item_cosmetics.sp#L52-L54

I'll close this issue, since this is not relevant to the plugin nor a problem with the project itself, but rather a generic **SourceMod** admin configuration.
